### ISSUE TITLE
It seems this repo no longer is maintained 

### ISSUE THREAD

**Issue by mo-esmp** [mohebifar/made-in-iran#211]
It's sad we no longer be able to find out about the new cool Iranian repo.

**Comment by yamin8000** [comment]
> 
> 
> It's sad we no longer be able to find out about the new cool Iranian repo.

Yeah, I think if owner doesn't want to maintain it he should transfer ownership or at the very least give some permission to other people who want to maintain this repo.

**Comment by amirbagh75** [comment]
I am now one of the collaborators of this repo.
Every Thursday I will check Pull requests/

**Comment by mamal72** [comment]
I'm closing this one as @amirbagh75 already responded here. Feel free to reopen if you have any objections. 👍
