### ISSUE TITLE
Talk about new files structure for repository

### ISSUE THREAD

**Issue by amirbagh75** [mohebifar/made-in-iran#213]
My suggestion: Each repository is a file (I hate merge conflicts)
For example we have `cpp` directory:

```bash
/cpp/repo1
/cpp/repo2
/cpp/repo3
```

`/cpp/repo1`  contents:
```text
amiremohamadi/DuckX
```

Currently, i have no idea how to naming the files.

**Comment by amirbagh75** [comment]
I think this is not work. we should make it easier. why not issues?

**Comment by amirbagh75** [comment]
Yes!, `issues` is the key.

**Comment by amirbagh75** [comment]
We use `issues` in [https://github.com/softwaretalks/newsletter](url) and everything works great.

**Comment by amirbagh75** [comment]
Finally, our system will look like this: 

1. Users create issues (based on a template) to introduce their repositories & categories.
2. If the issue is accepted, admins should close it with `verified` label.
3. On [closing issue event](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issues), actions starting.
4. Actions should validating issue contents and if everything is fine, then contents will be added to the README.md file. 

---

Sample issue template (YAML format):
## copy your repository link (example: https://github.com/softwaretalks/newsletter)
repoLink: ""

## current categories: 
## cpp
## reactjs
## php
## other
## golang
category: ""

**Comment by amirbagh75** [comment]
I think it's time to close this issue? @mohebifar

**Comment by mohebifar** [comment]
Yup :)
