### ISSUE TITLE
Add amirbagh75/The-dark-sides-of-being-a-SysAdmin

### ISSUE THREAD

**Issue by amirbagh75** [mohebifar/made-in-iran#217]
Repository name: `amirbagh75/The-dark-sides-of-being-a-SysAdmin`
Repository category: `other`

**Comment by amirbagh75** [comment]
Why Unrecognizable :(

**Comment by amirbagh75** [comment]
این رو ترجیحا اضافه نکنیمش. چون چیز خاصی نداره ریپوش. همینطوری واسه تست زدم اینجا

**Comment by mohebifar** [comment]
It's too late. :D

**Comment by amirbagh75** [comment]
آب که از سرگذشت چه یک وجب چه صد وجب
باشه پس
