### ISSUE TITLE
I don't see my item in the list.

### ISSUE THREAD

**Issue by hesmaili** [mohebifar/made-in-iran#27]
hi mohammad , i added my item 2 weeks ago in data.json as u mentioned in README and you merged it but i don't see it in the list now  . should i have done somethings special except PR ?? 😎👍
#26

**Comment by mohebifar** [comment]
At the time being, we do not have any automated procedure for generating README file out of data.json. You should wait.

**Comment by hesmaili** [comment]
ok . I thought README has been generated out of data.json and I missed somethings
thanks 👍👍
